//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tikubiken.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tikubiken.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string btntext_Cancel {
            get {
                return ResourceManager.GetString("btntext_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string btntext_Start {
            get {
                return ResourceManager.GetString("btntext_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log_compress {
            get {
                return ResourceManager.GetString("log_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copying file:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log_copyfile {
            get {
                return ResourceManager.GetString("log_copyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comparing files:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log_diff {
            get {
                return ResourceManager.GetString("log_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculating hash value for:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log_digest {
            get {
                return ResourceManager.GetString("log_digest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string log_writing {
            get {
                return ResourceManager.GetString("log_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable files (*.exe)|*.exe|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ofd_out_filter {
            get {
                return ResourceManager.GetString("ofd_out_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML files (*.xml)|*.xml|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ofd_src_filter {
            get {
                return ResourceManager.GetString("ofd_src_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file has an extension other than the default &quot;.exe&quot;. Do you want to add a default extension?
        ///(If the file extension is not &quot;.exe&quot;, the executable patch will not be generated.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string query_extension {
            get {
                return ResourceManager.GetString("query_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file already exists. Overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string query_overwrite {
            get {
                return ResourceManager.GetString("query_overwrite", resourceCulture);
            }
        }
    }
}
